#ifndef __time_monitor_h__
#define __time_monitor_h__


#include <linux/ioctl.h>
#include <linux/types.h>


#define TIME_MONITOR_DEVICE_NAME "time_monitor"
#define TIME_MONITOR_MINOR_NUMBER   253

#define MAX_STATS 600
#define OVERFLOW_BUFFER_YES 1
#define OVERFLOW_BUFFER_NO  0

#define TIME_MONITOR_IOCTL_ON                  _IOR(TIME_MONITOR_MINOR_NUMBER, 0, long)
#define TIME_MONITOR_IOCTL_OFF                 _IOR(TIME_MONITOR_MINOR_NUMBER, 1, long)
#define TIME_MONITOR_IOCTL_DUMP                _IOR(TIME_MONITOR_MINOR_NUMBER, 2, long)
#define TIME_MONITOR_IOCTL_REGISTER_THREAD     _IOR(TIME_MONITOR_MINOR_NUMBER, 3, long)
#define TIME_MONITOR_IOCTL_UNREGISTER_THREAD   _IOR(TIME_MONITOR_MINOR_NUMBER, 4, long)
#define TIME_MONITOR_IOCTL_THREAD_SLEEP        _IOR(TIME_MONITOR_MINOR_NUMBER, 5, long)
#define TIME_MONITOR_IOCTL_THREAD_WAKEUP       _IOR(TIME_MONITOR_MINOR_NUMBER, 6, long)
#define TIME_MONITOR_IOCTL_SET_DELTA			  _IOR(TIME_MONITOR_MINOR_NUMBER, 7, long)
#define TIME_MONITOR_IOCTL_READ_DELTA			  _IOR(TIME_MONITOR_MINOR_NUMBER, 8, long)
#define TIME_MONITOR_IOCTL_SET_POINTERS		  _IOR(TIME_MONITOR_MINOR_NUMBER, 9, long)


#define DEACTIVE 0x0000
#define WRITE_FLAGS 0x001f
#define READ_WRITE_MODE  0xc000
#define READ_BUFF_OR_WAKE_DATA  0x03ff

#define SCHED_ACTIVE 0x0001
#define INT_ACTIVE 0x0002
#define EXCEPTION_ACTIVE 0x0004
#define SOFTIRQ_ACTIVE 0x0008
#define SYSCALLS_ACTIVE 0x0010

#define SCHED_DEACTIVE 0xfffe
#define INT_DEACTIVE 0xfffd
#define EXCEPTION_DEACTIVE 0xfffb
#define SOFTIRQ_DEACTIVE 0xfff7
#define SYSCALLS_DEACTIVE 0xffef



#endif // __time_monitor_h__
